name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache UCD data
        uses: actions/cache@v4
        with:
          path: data/16.0.0/ucd
          key: ucd-16.0.0
      - name: Install test dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pytest
      - name: Generate Unicode lookup tables and tests
        run: make gen
      - name: Run tests
        run: pytest -q
